import { useEffect, useState } from 'react'

const invoice={po:'PO-24119',supplier:'Northstar Industrial Supplies',number:'INV-NS-8841',amount:'$18,742.50'}
const nav=[['dashboard','Dashboard'],['inbox','Inbox'],['processing','AI Processing'],['validation','Validation'],['maker','Maker Review'],['checker','Checker Review'],['export','ERP Export'],['audit','Audit Trail'],['pricing','Pricing']]
const status={Received:'received',Processing:'processing',Validation:'validation','Maker Review':'maker','Checker Review':'checker',Completed:'done'}
const Badge=({children})=><span className={`pill ${status[children]||'processing'}`}>{children}</span>
const Button=({children,onClick,kind='primary'})=><button className={`btn ${kind}`} onClick={onClick}>{children}</button>

function App(){
 const [page,setPage]=useState('overview'),[copilot,setCopilot]=useState(false),[step,setStep]=useState(0),[processing,setProcessing]=useState(false),[maker,setMaker]=useState(false),[exported,setExported]=useState(false),[notice,setNotice]=useState('')
 const toast=t=>{setNotice(t);setTimeout(()=>setNotice(''),2600)}
 const start=()=>{setPage('processing');setProcessing(true);setStep(0);[900,1750,2600,3450].forEach((delay,i)=>setTimeout(()=>setStep(i+1),delay));setTimeout(()=>{setProcessing(false);setPage('validation');toast('AI processing complete. Ready for validation.')},5050)}
 const go=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})}
 const shared={go,toast,start,maker,setMaker,exported,setExported,processing,step}
 const pages={overview:<Overview go={go}/>,dashboard:<Dashboard go={go}/>,inbox:<Inbox start={start}/>,processing:<Processing {...shared}/>,validation:<Validation go={go} toast={toast}/>,maker:<Maker {...shared}/>,checker:<Checker {...shared}/>,export:<Export {...shared}/>,audit:<Audit toast={toast}/>,pricing:<Pricing toast={toast}/>}
 return <div className="shell"><aside><div className="brand"><b>F</b>FlowLedger</div><small>WORKSPACE</small>{nav.map(([id,label])=><button className={page===id?'active':''} key={id} onClick={()=>go(id)}>{label}</button>)}<footer><b>AP Operations</b><br/>Production workspace</footer></aside><main><header><span>Invoice operations / <b>{page==='overview'?'Welcome':nav.find(x=>x[0]===page)?.[1]}</b></span><div className="headRight"><input placeholder="Search invoice, PO or supplier"/><span className="avatar">PS</span></div></header><section>{pages[page]}</section>{notice&&<div className="toast">{notice}</div>}<button className="copilotBtn" onClick={()=>setCopilot(!copilot)}>✦ AI Copilot</button>{copilot&&<Copilot close={()=>setCopilot(false)}/>}</main></div>
}
function Overview({go}){return <div className="overview"><article className="hero"><Badge>Processing</Badge><h1>Invoice intelligence, ready for your ERP.</h1><p>Extract, validate, and approve invoices with a traceable maker-checker workflow that keeps your team in control.</p><Button onClick={()=>go('inbox')}>Start Demo Journey</Button><div className="stats"><b>99.2%<small>field extraction accuracy</small></b><b>&lt; 2 min<small>average handling time</small></b><b>100%<small>audit-ready decisions</small></b></div></article><h2>A controlled path to posting</h2><div className="flow">{['Ingest','Extract','Validate','Maker','Checker','Export'].map((x,i)=><div key={x}><b>{i+1}</b>{x}</div>)}</div></div>}
function Dashboard({go}){return <><div className="heading"><div><h1>Good morning, Priya</h1><p>Here is what needs attention in accounts payable today.</p></div><Button kind="secondary" onClick={()=>go('inbox')}>Open inbox</Button></div><div className="metrics">{[['Invoices awaiting action','24'],['AI processing','8'],['Review exceptions','5'],['Straight-through rate','96.8%']].map(x=><article className="card metric" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><em>+12% this week</em></article>)}</div><div className="two"><article className="card"><h2>Invoice workload</h2><div className="bars">{[42,67,50,90,63,77,55].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></article><article className="card"><h2>Needs attention</h2><p><b>PO-24119</b><br/><small>Northstar · $60 freight variance</small></p><Button kind="secondary" onClick={()=>go('validation')}>Review</Button></article></div></>}
function Inbox({start}){return <><div className="heading"><div><h1>Purchase order inbox</h1><p>New invoices matched to open purchase orders.</p></div><Badge>Received</Badge></div><div className="two inbox"><article className="card invoice"><div><b>{invoice.po}</b><small>{invoice.number} · {invoice.supplier}</small></div><strong>{invoice.amount}</strong><Badge>Received</Badge><Button kind="secondary" onClick={start}>Process</Button></article><article className="card detail"><h2>{invoice.po}</h2><div className="paper">NORTHSTAR<br/><br/>Invoice {invoice.number}<hr/>Total due <b>{invoice.amount}</b></div><p>PO total <b>$18,950.00</b></p><p>Terms <b>Net 30</b></p><Button onClick={start}>Start AI Processing</Button></article></div></>}
function Processing({processing,step,go}){let values=[['Supplier','Northstar Industrial'],['Invoice date','01 Oct 2026'],['PO number','PO-24119'],['Total amount','$18,742.50']];return <><div className="heading"><div><h1>AI processing</h1><p>{invoice.number} · {invoice.supplier}</p></div><Badge>{processing?'Processing':'Validation'}</Badge></div><div className="two"><article className={`card document ${processing?'scanning':''}`}><h2>NORTHSTAR</h2><p>Invoice {invoice.number}</p><hr/><p>Manufacturing supplies <b>$17,850.00</b></p><p>GST <b>$892.50</b></p><p>Freight <b>$210.00</b></p><hr/><p><b>Total due {invoice.amount}</b></p></article><article className="card"><h2>{processing?'Extracting invoice values':'Extraction complete'}</h2><p>{processing?'AI is reading the document and filling structured fields as they are verified.':'All fields captured with source-linked confidence.'}</p>{processing&&<><div className="progress"><i style={{width:`${step*25}%`}}/></div><small>Document analysis in progress · {step} of 4 fields</small></>}<div className="checks">{values.map((x,i)=><div className={step>i?'revealed':''} key={x[0]}><small>{x[0]}</small>{step>i?<b>{x[1]}</b>:<span/>}</div>)}</div>{!processing&&<Button onClick={()=>go('validation')}>Continue to validation</Button>}</article></div></>}
function Validation({go,toast}){return <><div className="heading"><div><h1>Business validation</h1><p>Review AI-extracted values against the invoice and purchase order.</p></div><Badge>Validation</Badge></div><article className="card wide"><h2>Freight needs review</h2><p>Invoice freight is $210.00, $60.00 above the PO allowance. The delivery docket supports a carrier surcharge.</p><Button kind="secondary" onClick={()=>toast('AI rationale: surcharge is supported by the delivery docket.')}>View AI rationale</Button><Button onClick={()=>go('maker')}>Continue to Maker Review</Button></article></>}
function Maker({go,setMaker}){return <><div className="heading"><div><h1>Maker review</h1><p>Confirm coding and document the variance before checker approval.</p></div><Badge>Maker Review</Badge></div><article className="card wide"><h2>Review summary</h2><p>Freight variance acknowledged. Delivery docket supports the $60.00 surcharge.</p><label>Cost centre<input defaultValue="CC-4102 Operations"/></label><label>GL account<input defaultValue="520100 Freight & Delivery"/></label><p><input type="checkbox" defaultChecked/> I confirm the invoice, PO match, and coding are accurate.</p><Button kind="success" onClick={()=>{setMaker(true);go('checker')}}>Approve for checker</Button></article></>}
function Checker({go,maker}){return <><div className="heading"><div><h1>Checker approval</h1><p>Authorize the reviewed invoice for ERP export.</p></div><Badge>Checker Review</Badge></div><article className="card wide"><h2>Approval checklist</h2>{['PO match confirmed','Freight exception justified','Coding reviewed','Maker attestation verified'].map(x=><p key={x}>✓ {x}</p>)}<div className="signature">Digital signature<br/><b>Priya Shah</b><br/><Badge>Completed</Badge></div><Button kind="success" onClick={()=>maker?go('export'):go('maker')}>{maker?'Approve & authorize ERP export':'Return to maker'}</Button></article></>}
function Export({go,exported,setExported}){return <><div className="heading"><div><h1>ERP export</h1><p>Send the approved invoice to your production finance system.</p></div><Badge>{exported?'Completed':'Checker Review'}</Badge></div><article className="card wide"><h2>{exported?'Invoice posted successfully':'Approval trail complete'}</h2><p>{exported?'SAP document 5100027814 · Posted 01 Oct 2026, 10:44 IST':'SAP S/4HANA · Production is connected and ready.'}</p>{exported?<Button kind="secondary" onClick={()=>go('audit')}>View Audit Trail</Button>:<Button onClick={()=>setExported(true)}>Push to ERP</Button>}</article></>}
function Audit({toast}){return <><div className="heading"><div><h1>Audit trail</h1><p>A complete, tamper-evident history for {invoice.po}.</p></div><Button kind="secondary" onClick={()=>toast('Audit log prepared for download.')}>Export audit log</Button></div><article className="card timeline">{['Posted to SAP S/4HANA','Checker signature verified','Maker approval completed','Business validation flagged freight','Extraction completed','Invoice received'].map((x,i)=><p key={x}><b>{x}</b><br/><small>{i?'Priya Shah · 10:3'+i+' IST':'AP Automation · 10:44 IST'}</small></p>)}</article></>}
function Pricing({toast}){let plans=[['Starter','$249','Up to 500 invoices / month','AI extraction and validation','Two approval roles'],['Growth','$699','Up to 2,500 invoices / month','Maker-checker workflow','SAP S/4HANA export'],['Enterprise','Custom','Unlimited invoices','Custom ERP integrations','Dedicated environment']];return <><div className="pricingHead"><Badge>Processing</Badge><h1>Choose the control your AP team needs.</h1><p>Every plan includes the complete FlowLedger approval experience.</p></div><div className="plans">{plans.map((p,i)=><article className={`card plan ${i===1?'popular':''}`} key={p[0]}>{i===1&&<Badge>Processing</Badge>}<h2>{p[0]}</h2><strong>{p[1]} <small>{p[1][0]==='$'?'per month':'annual plan'}</small></strong><ul>{p.slice(2).map(x=><li key={x}>✓ {x}</li>)}</ul><Button kind={i===1?'primary':'secondary'} onClick={()=>toast(`${i===2?'Sales':'Trial'} request noted.`)}>{i===2?'Talk to sales':'Start free trial'}</Button></article>)}</div></>}
function Copilot({close}){return <aside className="copilot"><button onClick={close}>×</button><h2>✦ FlowLedger Copilot</h2><p>Context: PO-24119 · INV-NS-8841</p><button>Why was freight flagged?</button><button>Summarize PO variance</button><p>The $60 freight variance is supported by the delivery docket.</p></aside>}
export default App
