import { createRoot } from 'react-dom/client'
import App from './AppSaas.jsx'
import './styles.css'
import './polish.css'
import './integrations.css'
import './chart-fix.css'
import './dark-theme.css'
import './pdf-viewer.css'
import './chart-modern.css'
createRoot(document.getElementById('root')).render(<App />)
